import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {createStore} from '../src/store.mjs';
import {app} from '../src/server.mjs';

test('US catalog governance HTTP dependency works and preserves account/admin isolation',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'governance-http-')),path=join(dir,'test.sqlite');
 const store=createStore(path),server=app(store,{adminToken:'test-admin-token'});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 t.after(async()=>{await new Promise(resolve=>server.close(resolve));store.close();rmSync(dir,{recursive:true,force:true});});
 const base=`http://127.0.0.1:${server.address().port}`;
 const a=store.createUser(),b=store.createUser(),creator=store.createUser();
 const sa=store.createDeviceSession(a),sb=store.createDeviceSession(b);
 const db=new DatabaseSync(path),now=new Date().toISOString();
 db.prepare('INSERT INTO creator_profiles VALUES (?,?,1,?,?,NULL,?,?)').run('creator-profile',creator,'approved','{}',now,now);
 db.prepare('INSERT INTO packages VALUES (?,1,?,?,?)').run('public','published',JSON.stringify({ownerId:creator}),now);
 db.prepare('INSERT INTO packages VALUES (?,1,?,?,?)').run('private','draft',JSON.stringify({ownerId:creator}),now);db.close();
 const call=async(path,token,body,method=body?'POST':'GET')=>{const r=await fetch(base+path,{method,headers:{...(token?{Authorization:`Bearer ${token}`} : {}),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return [r.status,await r.json()];};
 assert.equal((await call('/v1/me/blocks'))[0],401);
 assert.deepEqual(await call('/v1/me/blocks',sa.token),[200,{items:[]}]);
 assert.equal((await call('/v1/me/blocks',sa.token,{packageId:'private'}))[0],404);
 assert.equal((await call('/v1/me/blocks',sa.token,{packageId:'public'}))[0],200);
 assert.equal((await call('/v1/me/blocks',sa.token))[1].items.length,1);
 assert.equal((await call('/v1/me/blocks',sb.token))[1].items.length,0);
 await call('/v1/me/blocks/creator-profile',sb.token,null,'DELETE');
 assert.equal((await call('/v1/me/blocks',sa.token))[1].items.length,1);
 const report=await call('/v1/me/reports',sa.token,{packageId:'public',reason:'abuse',details:'isolated test'});
 assert.equal(report[0],201);
 assert.equal((await call('/v1/me/reports/'+report[1].id,sb.token))[0],404);
 assert.equal((await call('/admin/reports',sa.token))[0],401);
 assert.equal((await call('/admin/reports','test-admin-token'))[1].items.length,1);
 assert.equal((await call('/admin/reports/'+report[1].id,'test-admin-token',{version:1,status:'in_review',resolution:'review test'}))[0],200);
 assert.equal((await call('/admin/reports/'+report[1].id,'test-admin-token',{version:1,status:'in_review',resolution:'stale'}))[0],409);
 await call('/v1/me/blocks/creator-profile',sa.token,null,'DELETE');
 assert.equal((await call('/v1/me/blocks',sa.token))[1].items.length,0);
});
