import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createStore } from '../src/store.mjs';
import { app } from '../src/server.mjs';
import { authorizedClip } from '../src/delivery.mjs';

test('empty packages grow by real uploads and individual visibility preserves other videos', async t => {
  const directory=await mkdtemp(join(tmpdir(),'package-videos-')),store=createStore();
  const server=app(store,{adminToken:'admin',mediaDirectory:directory,inspector:async()=>({status:'checked',durationSeconds:1})});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  t.after(async()=>{await new Promise(r=>server.close(r));store.close();await rm(directory,{recursive:true});});
  const base=`http://127.0.0.1:${server.address().port}`;
  const call=async(path,body)=>{const r=await fetch(base+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer admin','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};
  let result=await call('/admin/packages',{title:'角色',description:'背景',format:'package',tags:['科幻未来'],clips:[]});
  assert.equal(result.status,201);let item=result.data;const path='/admin/packages/'+item.id;
  assert.equal((await call(path+'/review',{version:item.version,decision:'approved',note:'ok',rightsConfirmed:true,rightsReference:'R'})).status,409);
  assert.equal((await call(path+'/publish',{version:item.version})).status,409);
  const video=Buffer.alloc(32);video.write('ftyp',4);
  const upload=async(version,body=video,token='admin')=>{const r=await fetch(base+path+'/clips?filename='+encodeURIComponent('舞蹈.mp4'),{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':'video/mp4','If-Match':String(version)},body});return {status:r.status,data:await r.json()};};
  assert.equal((await upload(item.version,video,'wrong')).status,401);
  assert.equal((await upload(item.version,Buffer.alloc(32))).status,415);
  assert.equal(store.get(item.id).clips.length,0);assert.equal((await readdir(directory)).length,0);
  result=await upload(item.version);assert.equal(result.status,201);item=result.data;
  assert.equal(item.clips.length,1);assert.equal(item.clips[0].title,'舞蹈');const first=item.clips[0].id;
  assert.equal((await upload(1)).status,409);
  item=(await call(path+`/clips/${first}/withdraw`,{version:item.version})).data;
  assert.equal(item.clips[0].visibility,'withdrawn');
  item=(await call(path+`/clips/${first}/restore`,{version:item.version})).data;
  assert.equal(item.clips[0].visibility,undefined);
  item=(await call(path+`/clips/${first}/inspect`,{})).data;
  item=store.attachCover(item.id,item.version,{id:'cover'});
  item=(await call(path+'/review',{version:item.version,decision:'approved',note:'ok',rightsConfirmed:true,rightsReference:'R'})).data;
  item=(await call(path+'/publish',{version:item.version})).data;
  assert.equal(item.status,'published');
  result=await upload(item.version);assert.equal(result.status,201);item=result.data;const second=item.clips[1].id;
  assert.deepEqual((await call('/v1/packages/'+item.id)).data.clips.map(c=>c.id),[first]);
  const publish={version:item.version,rightsConfirmed:true,rightsReference:'R',note:'核对通过'};
  assert.equal((await call(path+`/clips/${second}/publish`,publish)).status,409);
  item=(await call(path+`/clips/${second}/inspect`,{})).data;
  assert.equal((await fetch(base+'/v1/media/'+item.clips[1].media.id)).status,404);
  assert.equal((await call(path+`/clips/${second}/publish`,{version:item.version,rightsConfirmed:false})).status,400);
  item=(await call(path+`/clips/${second}/publish`,{...publish,version:item.version})).data;
  assert.equal((await call('/v1/packages/'+item.id)).data.clips.length,2);
  const firstMedia=item.clips[0].media.id;
  item=(await call(path+`/clips/${first}/withdraw`,{version:item.version})).data;
  assert.deepEqual((await call('/v1/packages/'+item.id)).data.clips.map(c=>c.id),[second]);
  assert.equal((await fetch(base+'/v1/media/'+firstMedia)).status,404);
  assert.equal((await fetch(base+'/v1/media/'+firstMedia+'/thumbnail')).status,404);
  assert.equal(authorizedClip({entitlements:()=>[{package_id:item.id,status:'active'}],get:()=>item},'u',item.id,first),null);
  assert.equal((await call(path+`/clips/${first}/publish`,{...publish,version:item.version-1})).status,409);
  item=(await call(path+`/clips/${second}/withdraw`,{version:item.version})).data;
  assert.equal((await call('/v1/packages/'+item.id)).status,404);
  assert.equal((await call('/v1/catalog')).data.items.length,0);
  item=(await call(path+`/clips/${first}/publish`,{...publish,version:item.version})).data;
  assert.equal((await call('/v1/packages/'+item.id)).data.clips.length,1);
});
