enum CommunityLicense { personalUse, commercialUse, publicDomain }

enum CommunityRightsStatus { pending, verified, removed }

enum DevicePlaylistTarget { local, bluetooth }

enum ContentDownloadStatus { notDownloaded, downloading, downloaded, failed }

class CommunityContent {
  const CommunityContent({
    required this.id,
    required this.title,
    required this.creatorName,
    required this.summary,
    required this.category,
    required this.license,
    required this.rightsStatus,
    required this.playlistTarget,
    required this.supportedModels,
    required this.fileSizeMb,
    required this.durationSeconds,
    required this.version,
    this.previewAsset,
    this.thumbnailAsset,
  });

  final String id;
  final String title;
  final String creatorName;
  final String summary;
  final String category;
  final CommunityLicense license;
  final CommunityRightsStatus rightsStatus;
  final DevicePlaylistTarget playlistTarget;
  final List<String> supportedModels;
  final int fileSizeMb;
  final int durationSeconds;
  final String version;
  final String? previewAsset;
  final String? thumbnailAsset;

  bool get canDownload => rightsStatus == CommunityRightsStatus.verified;
  bool get canInstall => canDownload;
}

const communityPreviewItems = <CommunityContent>[
  CommunityContent(
    id: 'hildors_demo_01',
    title: 'HILDORS 全息展示 01',
    creatorName: 'HILDORS Demo',
    summary: '为全息座舱优化的横屏角色展示，可在手机端直接预览。',
    category: '角色',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.local,
    supportedModels: ['P20', 'P11'],
    fileSizeMb: 12,
    durationSeconds: 63,
    version: '1.0',
    previewAsset: 'assets/videos/showcase/showcase_01.mp4',
    thumbnailAsset: 'assets/images/video_thumbnails/showcase_01.jpg',
  ),
  CommunityContent(
    id: 'hildors_demo_02',
    title: 'HILDORS 全息展示 02',
    creatorName: 'HILDORS Demo',
    summary: '适合开机自动播放列表的竖屏角色演示内容。',
    category: '角色',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.local,
    supportedModels: ['P20', 'P11'],
    fileSizeMb: 2,
    durationSeconds: 10,
    version: '1.0',
    previewAsset: 'assets/videos/showcase/showcase_02.mp4',
    thumbnailAsset: 'assets/images/video_thumbnails/showcase_02.jpg',
  ),
  CommunityContent(
    id: 'hildors_demo_03',
    title: 'HILDORS 音乐联动 01',
    creatorName: 'HILDORS Demo',
    summary: '连接蓝牙音源后展示的音乐氛围演示内容。',
    category: '音乐',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.bluetooth,
    supportedModels: ['P20'],
    fileSizeMb: 1,
    durationSeconds: 10,
    version: '1.0',
    previewAsset: 'assets/videos/showcase/showcase_03.mp4',
    thumbnailAsset: 'assets/images/video_thumbnails/showcase_03.jpg',
  ),
  CommunityContent(
    id: 'hildors_demo_04',
    title: 'HILDORS 音乐联动 02',
    creatorName: 'HILDORS Demo',
    summary: '适合蓝牙播放状态的竖屏全息氛围内容。',
    category: '音乐',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.bluetooth,
    supportedModels: ['P20'],
    fileSizeMb: 4,
    durationSeconds: 10,
    version: '1.0',
    previewAsset: 'assets/videos/showcase/showcase_04.mp4',
    thumbnailAsset: 'assets/images/video_thumbnails/showcase_04.jpg',
  ),
  CommunityContent(
    id: 'concept_cyber_ronin',
    title: '影刃武士',
    creatorName: 'HILDORS Lab',
    summary: '原创赛博武士角色概念内容。',
    category: '角色',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.local,
    supportedModels: ['P20', 'P11'],
    fileSizeMb: 8,
    durationSeconds: 18,
    version: 'Concept',
    thumbnailAsset: 'assets/images/content_thumbnails/cyber_ronin.jpg',
  ),
  CommunityContent(
    id: 'concept_celestial_mage',
    title: '星轨法师',
    creatorName: 'HILDORS Lab',
    summary: '原创星际法师角色概念内容。',
    category: '角色',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.local,
    supportedModels: ['P20', 'P11'],
    fileSizeMb: 9,
    durationSeconds: 20,
    version: 'Concept',
    thumbnailAsset: 'assets/images/content_thumbnails/celestial_mage.jpg',
  ),
  CommunityContent(
    id: 'concept_neon_dancer',
    title: '霓虹舞者',
    creatorName: 'HILDORS Lab',
    summary: '原创音乐联动舞者概念内容。',
    category: '音乐',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.bluetooth,
    supportedModels: ['P20'],
    fileSizeMb: 7,
    durationSeconds: 16,
    version: 'Concept',
    thumbnailAsset: 'assets/images/content_thumbnails/neon_dancer.jpg',
  ),
  CommunityContent(
    id: 'concept_clockwork_explorer',
    title: '时轮探险家',
    creatorName: 'HILDORS Lab',
    summary: '原创机械探险家角色概念内容。',
    category: '角色',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.local,
    supportedModels: ['P20', 'P11'],
    fileSizeMb: 10,
    durationSeconds: 22,
    version: 'Concept',
    thumbnailAsset: 'assets/images/content_thumbnails/clockwork_explorer.jpg',
  ),
  CommunityContent(
    id: 'concept_lunar_guardian',
    title: '月蚀守卫',
    creatorName: 'HILDORS Lab',
    summary: '原创月夜守卫角色概念内容。',
    category: '角色',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.local,
    supportedModels: ['P20', 'P11'],
    fileSizeMb: 9,
    durationSeconds: 19,
    version: 'Concept',
    thumbnailAsset: 'assets/images/content_thumbnails/lunar_guardian.jpg',
  ),
  CommunityContent(
    id: 'concept_deep_sea_oracle',
    title: '深海先知',
    creatorName: 'HILDORS Lab',
    summary: '原创深海氛围角色概念内容。',
    category: '角色',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.local,
    supportedModels: ['P20', 'P11'],
    fileSizeMb: 8,
    durationSeconds: 18,
    version: 'Concept',
    thumbnailAsset: 'assets/images/content_thumbnails/deep_sea_oracle.jpg',
  ),
  CommunityContent(
    id: 'concept_crystal_knight',
    title: '晶核骑士',
    creatorName: 'HILDORS Lab',
    summary: '原创水晶机甲角色概念内容。',
    category: '角色',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.local,
    supportedModels: ['P20', 'P11'],
    fileSizeMb: 11,
    durationSeconds: 24,
    version: 'Concept',
    thumbnailAsset: 'assets/images/content_thumbnails/crystal_knight.jpg',
  ),
  CommunityContent(
    id: 'concept_space_pilot',
    title: '深空领航员',
    creatorName: 'HILDORS Lab',
    summary: '原创复古太空角色概念内容。',
    category: '角色',
    license: CommunityLicense.personalUse,
    rightsStatus: CommunityRightsStatus.verified,
    playlistTarget: DevicePlaylistTarget.local,
    supportedModels: ['P20', 'P11'],
    fileSizeMb: 8,
    durationSeconds: 17,
    version: 'Concept',
    thumbnailAsset: 'assets/images/content_thumbnails/space_pilot.jpg',
  ),
];
